python3-setproctitle: Add missing rdep on libatomic-dev for ptest
Issue: LINUXEXEC-34705

Fixes:
  E           subprocess.CalledProcessError: Command '['cc', '-I/usr/include/python3.13', '-I/usr/include/python3.13', '-o', '/usr/lib64/python3-setproctitle/ptest/tests/pyrun3.13', '/usr/lib64/python3-setproctitle/ptest/tests/pyrun.c', '-L/usr/lib64', '-lpython3.13', '-ldl', '-lpthread', '-latomic', '-lm', '-L/usr/lib']' returned non-zero exit status 1.

  ../../python3.13/subprocess.py:421: CalledProcessError
  ERROR: tests/setproctitle_test.py:test_embedded

  E           subprocess.CalledProcessError: Command '['cc', '-I/usr/include/python3.13', '-I/usr/include/python3.13', '-o', '/usr/lib64/python3-setproctitle/ptest/tests/pyrun3.13', '/usr/lib64/python3-setproctitle/ptest/tests/pyrun.c', '-L/usr/lib64', '-lpython3.13', '-ldl', '-lpthread', '-latomic', '-lm', '-L/usr/lib']' returned non-zero exit status 1.

  ../../python3.13/subprocess.py:421: CalledProcessError
  ERROR: tests/setproctitle_test.py:test_embedded_many_args

(LOCAL REV: NOT UPSTREAM) -- sent to meta-oe on 20250512

Signed-off-by: Mingli Yu <mingli.yu@windriver.com>