libcamera: fix compile failure on 32 bit target
When debug build is enabled, build failed on 32 bit target,
such as qemux86
$ echo 'MACHINE = "qemux86"' >> conf/local.conf
$ echo 'DEBUG_BUILD = "1"  >> conf/local.conf
$ bitbake libcamera
...
|../git/src/libcamera/pipeline/simple/simple.cpp:1564:9: error:
'media' may be used uninitialized [-Werror=maybe-uninitialized]
| 1564 |         if (!media)
|      |         ^~
|../git/src/libcamera/pipeline/simple/simple.cpp:1553:22: note:
'media' was declared here
| 1553 |         MediaDevice *media;
...

Backport a patch from upstream to fix the issue

Issue: LIN1025-5540
(LOCAL REV: NOT UPSTREAM) -- sent to OE walnascar on 20251027

Signed-off-by: Hongxu Jia <hongxu.jia@windriver.com>